spring:
  cloud:
    discovery:
      enabled: false
  config:
    enabled: true
    import: optional:configserver:${CONFIG_SERVICE_URL:http://127.0.0.1:8888}
    #import: optional:configserver:http://DESKTOP--ALPHOU:8011
  instance:
    prefer-ip-address: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    transport:
      jersey:
        enabled: false

server:
  port: 8761