spring:
  cloud:
    discovery:
      enabled: false
  instance:
    prefer-ip-address: true
  config:
    enabled: true
    import: optional:configserver:${CONFIG_SERVICE_URL}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    transport:
      jersey:
        enabled: false

server:
  port: 8761