spring:
  cloud:
    discovery:
      enabled: false
  instance:
    prefer-ip-address: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    transport:
      jersey:
        enabled: false

server:
  port: 8761