server:
  port: 8015

# PostgreSQL Database Configuration
spring:
  datasource:
   url: jdbc:postgresql://192.168.154.250:5434/orders_db
   username: alphou
   password: alphou
   driver-class-name: org.postgresql.Driver
  
  # Hibernate (JPA) Configuration
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect