server:
  port: 8014

# MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://${PRODUCTS_DB_HOST}:${PRODUCTS_PORT}/${PRODUCTS_DB}
    username: ${PRODUCTS_DB_USERNAME}
    password: ${PRODUCTS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Hibernate (JPA) Configuration
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true