server:
  port: 8014

# MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://192.168.154.250:3307/productss_db
    username: alphou
    password: alphou
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Hibernate (JPA) Configuration
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect