server:
  port: 8016

spring:
  data:
    mongodb:
      uri: mongodb://${USER_MONGO_DB_USERNAME}:${USER_MONGO_DB_PASSWORD}@${MONGO_SERVER_HOST}:${MONGO_SERVER_PORT}/${USER_MONGO_DB_NAME} # MongoDB connection URI

logging:
  level:
    org.springframework.data.mongodb: DEBUG # Enables debug logging for MongoDB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true